#!/bin/bash
# Assign unique IPv6 addresses to relay identities on each physical box.
#
# Each relay identity gets its own IPv6 address from the box's /64 prefix.
# Addresses are made persistent via systemd-networkd drop-in config.
#
# Usage:
#   ./scripts/assign-relay-ipv6.sh [--dry-run]
#
# Prerequisites:
#   - SSH access to relay boxes (root@box-hetzner-nuremberg.macula.io etc.)
#   - Each box has an existing IPv6 /64 allocation from its provider
#   - The identity list is read from the relay's MACULA_RELAY_IDENTITIES env var

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DRY_RUN="${1:-}"

# ── Box definitions ───────────────────────────────────────────────
# Format: BOXNAME|SSH_HOST|IPV6_PREFIX
# The prefix is the box's /64 — identities get sequential ::100, ::101, etc.
# ::1 is reserved for the box itself.
BOXES=(
  "box-hetzner-nuremberg|root@91.98.238.177|2a01:4f8:1c1f:8ab8"
  "box-hetzner-helsinki|root@95.216.141.48|2a01:4f9:c014:4259"
  "box-linode-amsterdam|root@172.235.174.211|2600:3c0e:e001:ec"
)

# ── Helper: parse identity hostname from MACULA_RELAY_IDENTITIES ──
# Input:  "relay-be-brussels.macula.io:Brussels:BE:50.8503:4.3517,..."
# Output: one hostname per line
parse_identity_hostnames() {
  echo "$1" | tr ',' '\n' | cut -d: -f1
}

# ── Main loop ─────────────────────────────────────────────────────
for box_def in "${BOXES[@]}"; do
  IFS='|' read -r BOX_NAME SSH_HOST IPV6_PREFIX <<< "${box_def}"

  echo ""
  echo "=== ${BOX_NAME} (${SSH_HOST}) ==="
  echo "    IPv6 prefix: ${IPV6_PREFIX}::/64"

  # Get current identity list from the running relay container
  IDENTITIES=$(ssh -o StrictHostKeyChecking=no "${SSH_HOST}" \
    "docker exec macula-relay printenv MACULA_RELAY_IDENTITIES 2>/dev/null || echo ''" 2>/dev/null)

  if [ -z "${IDENTITIES}" ]; then
    echo "    [skip] No MACULA_RELAY_IDENTITIES found in relay container"
    continue
  fi

  # Parse hostnames
  HOSTNAMES=$(parse_identity_hostnames "${IDENTITIES}")
  TOTAL=$(echo "${HOSTNAMES}" | wc -l)
  echo "    Found ${TOTAL} relay identities"

  # Build the address assignment list
  # Start at ::100 to leave room for box address (::1) and future use
  INDEX=256  # 0x100
  ADDR_LIST=""
  ADDR_MAP=""

  while IFS= read -r hostname; do
    HEX_INDEX=$(printf '%x' ${INDEX})
    ADDR="${IPV6_PREFIX}::${HEX_INDEX}"
    ADDR_LIST="${ADDR_LIST}${ADDR}/64\n"
    ADDR_MAP="${ADDR_MAP}    ${ADDR}  →  ${hostname}\n"
    INDEX=$((INDEX + 1))
  done <<< "${HOSTNAMES}"

  echo ""
  echo "    Address range: ${IPV6_PREFIX}::100 → ${IPV6_PREFIX}::$(printf '%x' $((INDEX - 1)))"

  if [ "${DRY_RUN}" = "--dry-run" ]; then
    echo ""
    echo "    [dry-run] Would assign ${TOTAL} addresses. First 5:"
    echo -e "${ADDR_MAP}" | head -5
    echo "    ..."
    continue
  fi

  # Detect network interface on the remote box
  IFACE=$(ssh -o StrictHostKeyChecking=no "${SSH_HOST}" \
    "ip -6 route show default | head -1 | awk '{for(i=1;i<=NF;i++) if(\$i==\"dev\") print \$(i+1)}'" 2>/dev/null)

  if [ -z "${IFACE}" ]; then
    echo "    [error] Could not detect network interface"
    continue
  fi

  echo "    Interface: ${IFACE}"
  echo "    Assigning ${TOTAL} IPv6 addresses..."

  # Generate the systemd-networkd drop-in for persistent addresses
  # Also assign them immediately with `ip addr add`
  NETWORKD_ADDRS=""
  INDEX=256
  while IFS= read -r hostname; do
    HEX_INDEX=$(printf '%x' ${INDEX})
    ADDR="${IPV6_PREFIX}::${HEX_INDEX}"

    NETWORKD_ADDRS="${NETWORKD_ADDRS}[Address]\nAddress=${ADDR}/64\n\n"
    INDEX=$((INDEX + 1))
  done <<< "${HOSTNAMES}"

  # Apply addresses immediately + persist via systemd-networkd drop-in
  ssh -o StrictHostKeyChecking=no "${SSH_HOST}" bash -s <<REMOTE_SCRIPT
set -e

# Create systemd-networkd drop-in directory
mkdir -p /etc/systemd/network/10-${IFACE}.network.d

# Write persistent address config
cat > /etc/systemd/network/10-${IFACE}.network.d/relay-ipv6.conf << 'NETEOF'
# Macula relay identity IPv6 addresses
# Auto-generated by assign-relay-ipv6.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# ${TOTAL} relay identities on ${IPV6_PREFIX}::/64
#
$(echo -e "${NETWORKD_ADDRS}")
NETEOF

# Apply addresses immediately (non-destructive — skips if already assigned)
INDEX=256
echo "${HOSTNAMES}" | while IFS= read -r hostname; do
  HEX_INDEX=\$(printf '%x' \${INDEX})
  ADDR="${IPV6_PREFIX}::\${HEX_INDEX}/64"
  if ! ip -6 addr show dev ${IFACE} | grep -q "${IPV6_PREFIX}::\${HEX_INDEX}"; then
    ip -6 addr add \${ADDR} dev ${IFACE} 2>/dev/null || true
  fi
  INDEX=\$((INDEX + 1))
done

# Count assigned addresses
ASSIGNED=\$(ip -6 addr show dev ${IFACE} scope global | grep -c "inet6" || echo 0)
echo "Assigned. Total global IPv6 addresses on ${IFACE}: \${ASSIGNED}"
REMOTE_SCRIPT

  echo "    Done. Addresses are persistent (systemd-networkd drop-in)."
done

echo ""
echo "=== Summary ==="
echo "Addresses assigned. To verify:"
for box_def in "${BOXES[@]}"; do
  IFS='|' read -r BOX_NAME SSH_HOST IPV6_PREFIX <<< "${box_def}"
  echo "  ssh ${SSH_HOST} 'ip -6 addr show scope global | grep -c inet6'"
done
echo ""
echo "Next: run setup-relay-dns-v6.sh to create AAAA records"
